- platform: moon
- platform: command_line
  name: Raspberry Pi 4 Temperature
  command: !secret command_line_pi_temperature
  unit_of_measurement: “°C”
  value_template: ‘{{ value | multiply(0.001) }}’